# Generated by Django 5.0 on 2025-04-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0003_alter_address_id_alter_letting_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
